version: "3"
services:
  migration-server:
    image: ramesesinc/filipizen-server:0.0.1
    container_name: filipizen-server
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    ports:
      - "5000:5000"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./_custom/env.conf
    